name: ai-code-review
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - pygithub
    - gitpython
    - pyyaml
    - rich
    - anthropic
    - openai
    - chardet